// <auto-generated />
using System;
using APIBank.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace APIBank.Migrations
{
    [DbContext(typeof(TestAppContext))]
    [Migration("20210326125258_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("APIBank.Models.BankRecord", b =>
                {
                    b.Property<int>("BankRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Cash")
                        .HasColumnType("float");

                    b.Property<int?>("CurrencyIdCurrencyItemId")
                        .HasColumnType("int");

                    b.Property<int?>("PersonIdPersonNameId")
                        .HasColumnType("int");

                    b.HasKey("BankRecordId");

                    b.HasIndex("CurrencyIdCurrencyItemId");

                    b.HasIndex("PersonIdPersonNameId");

                    b.ToTable("BankRecords");
                });

            modelBuilder.Entity("APIBank.Models.CurrencyItem", b =>
                {
                    b.Property<int>("CurrencyItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CurrencyLong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrencyShort")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CurrencyItemId");

                    b.ToTable("CurrencyItems");
                });

            modelBuilder.Entity("APIBank.Models.PersonName", b =>
                {
                    b.Property<int>("PersonNameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PersonFam")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonNameId");

                    b.ToTable("PersonNames");
                });

            modelBuilder.Entity("APIBank.Models.BankRecord", b =>
                {
                    b.HasOne("APIBank.Models.CurrencyItem", "CurrencyId")
                        .WithMany()
                        .HasForeignKey("CurrencyIdCurrencyItemId");

                    b.HasOne("APIBank.Models.PersonName", "PersonId")
                        .WithMany()
                        .HasForeignKey("PersonIdPersonNameId");

                    b.Navigation("CurrencyId");

                    b.Navigation("PersonId");
                });
#pragma warning restore 612, 618
        }
    }
}
